version: '3.7'

services:
  database:
    image: 'postgres:10.4'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data